### ISSUE TITLE
redirect to http://33.33.33.10/shopware/recovery/install/

### ISSUE THREAD

**Issue by codergeek121** [shopwareLabs/shopware-vagrant#1]
Hi,
I cloned the box and uncommented the #-shopware. After vagrant up is done, and I visit 33.33.33.10/shopware I get redirected to http://33.33.33.10/shopware/recovery/install/ and get a blank page. Any ideas?

**Comment by bcremer** [comment]
Can you please elaborate what you mean by the following:
> and uncommented the #-shopware

**Comment by codergeek121** [comment]
I changed `#- shopware` to `- shopware` in the playbook.yml before running vagrant.

**Comment by bcremer** [comment]
Ok, automatic shopware provisioning is not supported yet. We should have completely removed the `shopware` role before release.

Please see https://devdocs.shopware.com/developers-guide/vagrant-phpstorm/ for manual shopware installation.

Sorry for the confusion.
