### ISSUE TITLE
Add PHP 7 ioncube-loader

### ISSUE THREAD

**Issue by bcremer** [shopwareLabs/shopware-vagrant#12]
See: http://blog.ioncube.com/2016/09/15/php-7-ioncube-loaders/

**Comment by bestit-tkellner** [comment]
i create a pr for this:
https://github.com/shopwareLabs/shopware-vagrant/pull/14

**Comment by bcremer** [comment]
Fixed by #14 by @bestit-tkellner :+1:

**Comment by tobiasgraeber** [comment]
Is there anything linke this also to be done left for PHP 7.1 ?
Getting: Site error: the ionCube PHP Loader needs to be installed. This is a widely used PHP extension for running ionCube protected PHP code, website security and malware blocking. Please visit get-loader.ioncube.com for install assistance.

on 7.1

**Comment by teiling88** [comment]
Hey @tobiasgraeber,

at the moment no ioncube loader for php 7.1 is available. 

Greetings
