### ISSUE TITLE
Not able to switch php version

### ISSUE THREAD

**Issue by numediaweb** [shopwareLabs/shopware-vagrant#22]
I tried switching the PHP version on the vagrant machine (after ssh)
```
changephp_7.0
changephp_5.6
```

And I get this error
```
vagrant@registerbyemail:~/bin$ changephp_5.6
: No such file or directory
```

Any hints? :)

**Comment by larsbo** [comment]
sounds like #9 
Do you use windows? Did you pull the last version of shopware-vagrant?

**Comment by numediaweb** [comment]
I finally found that If you edited those files on a Windows machine, then you will need to remove CRLF characters on them
```
dos2unix /home/vagrant/bin/changephp_5.6 && dos2unix /home/vagrant/bin/changephp_7.0 && dos2unix /home/vagrant/bin/changephp_7.1 
```

This fixed it so it has no relation with this the vagrant setup in itself.

Thanks
