### ISSUE TITLE
mysql connection error

### ISSUE THREAD

**Issue by MartinRaitza** [shopwareLabs/shopware-vagrant#29]
The install_shopware script does not work because it is not possible to connect to mysql with your configuration.

Change the mysql_root_password  from root to shopware 
in file ansible/roles/mysql/defaults/main.yml

This will fix the bug and it will be possible to connect via adminer.php (user: root, password: shopware)

**Comment by teiling88** [comment]
Hey Martin,

i created an pull request for your issue #30 

Next time - feel free to create your own pull request ;-)

**Comment by bcremer** [comment]
The default mysql root user password for this vagrant box is `shopware` as configured in the vagrantfile, see here: https://github.com/shopwareLabs/shopware-vagrant/blob/ef0edffff9b76bd8f57d5e9d4065fba0205a3af2/Vagrantfile#L32

Further I am not able to reproduce your issue.

Please run the following commands to get a fresh setup of the box:

```
vagrant destroy
vagrant up
vagrant ssh
install_shopware
```

**Comment by bcremer** [comment]
@MartinRaitza Which version of vagrant do you use (`vagrant -v`).
There is a bug in vagrant 1.8.1 that prevents the extra_vars defined in https://github.com/shopwareLabs/shopware-vagrant/blob/ef0edffff9b76bd8f57d5e9d4065fba0205a3af2/Vagrantfile#L32 to work as intended.

https://github.com/mitchellh/vagrant/issues/6726

I'll look for a work around.

**Comment by bcremer** [comment]
@MartinRaitza applied your proposed fix. That should fix that problem for your. Thank you very much for reporting.

**Comment by MartinRaitza** [comment]
@bcremer Yep, I tried it with vagrant 1.8.1. I updated my machine and it works now.
Thank you for your quick response!
