### ISSUE TITLE
Don't use 33.33.33.10 as IP Address for Vagrant

### ISSUE THREAD

**Issue by darookee** [shopwareLabs/shopware-vagrant#3]
There are [reserved IP addresses](https://en.wikipedia.org/wiki/Reserved_IP_addresses) for this kind of usage. Also [this](https://www.drupal.org/node/1854010).

**Comment by bcremer** [comment]
+1

Seems like 33.33.33.10 was in the vagrant documentation in the past, but it's not recommended anymore. 
Also  33.33.33.10 seems to be a IP address block owned by the Department of Defense.

See:
- http://serverfault.com/questions/438147/why-do-vagrant-docs-suggest-using-public-ip-address-33-33-33-10-for-local-vms
- https://www.drupal.org/node/1854010

**Comment by bcremer** [comment]
@darookee It's finally resolved. Thanks for your patience.
