### ISSUE TITLE
SYNCED FOLDERS 

### ISSUE THREAD

**Issue by xhepigerta** [shopwareLabs/shopware-vagrant#32]
After installing  can't find the shopware folder  to edit.

**Comment by bcremer** [comment]
The files are not synced to a host directory because of performance issues. Instead you should use SSH/SCP to access files on the virtual machine. Please see our dokumentation on how to sync files via SCP here: https://developers.shopware.com/developers-guide/vagrant-phpstorm/#deploy-with-phpstorm

**Comment by alexschwarz89** [comment]
Should be documented, as i ran into the same question.
