### ISSUE TITLE
Upgrade to Ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by mpathy** [shopwareLabs/shopware-vagrant#34]
Hi there.. Now that the current LTS version of Ubuntu is out there for almost a year, and includes PHP7 by default and other things that make such a setup run even more smooth than before, would you maybe update this vagrant box or make a new one?

**Comment by bcremer** [comment]
Fixed with commit https://github.com/shopwareLabs/shopware-vagrant/commit/69f8ca62437a8376949c434235e7026ebcc504a3.

Thanks for the heads up :+1:
