### ISSUE TITLE
ansible-playbook error

### ISSUE THREAD

**Issue by quantatheist** [shopwareLabs/shopware-vagrant#45]
I have Vagrant 2.1.5 installed and a fresh cloned repository. 
When `vagrant up` runs, it throws this error:

`TASK [common : be sure ntpd is running and enabled] ****************************
fatal: [default]: FAILED! => {"changed": false, "msg": "value of state must be one of: reloaded, restarted, started, stopped, got: running"}
        to retry, use: --limit @/vagrant/ansible/playbook.retry`

`PLAY RECAP *********************************************************************
default                    : ok=7    changed=5    unreachable=0    failed=1`

`Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.`

**Comment by MrSnoozles** [comment]
I'm getting the same error. I'm using Windows 10 as host OS and haven't tried if the error occurrs on other systems yet. Is there a workaround for the error?

**Comment by Samb92** [comment]
I'm getting this error on Arch Linux, too.

**Comment by Dwza** [comment]
This issue was fixed. @samb92 Commentig something out just skips it, thats not a fix or workaround. And reading the issue clearly says what to do :) Anyways, this issue can be closed.
