### ISSUE TITLE
Upgrade php

### ISSUE THREAD

**Issue by sebastien-fauvel** [shopwareLabs/shopware-vagrant#5]
The php version shipped with the box is too old for Shopware 5.2. I had to run:
```bash
sudo apt-get update
sudo do-release-upgrade -d
```
to upgrade Ubuntu first, which installs php7.

Also the zip extension for php is missing, it can be installed afterwards with:
```bash
sudo apt-get install php7.0-zip
sudo apachectl restart
```

Does any upgrade already exist for the base box? What are you using in dev at Shopware?

**Comment by bcremer** [comment]
Most people are using a locally installed PHP and Apache on their linux and mac machines.
You should be able update the whole box to Ubuntu 16.04 (https://github.com/shopwareLabs/shopware-vagrant/blob/master/vagrant/Vagrantfile#L8).

If you can get it running I am happy to merge your pull request :)

**Comment by sebastien-fauvel** [comment]
I'll give it a try! Upgrading Ubuntu to 16.04 from within the old box worked like a charm.

**Comment by sebastien-fauvel** [comment]
It was simpler to only upgrade php in the end. Done in https://github.com/shopwareLabs/shopware-vagrant/pull/6 and tested with Shopware [v5.2.0-BETA1](https://github.com/shopware/shopware/commit/baba67597f9e3a1b747e660acd4c9bd9f419f68a).

**Comment by BlueWolf-Produktion** [comment]
I could update the PHP version with this: https://www.digitalocean.com/community/tutorials/how-to-upgrade-to-php-7-on-ubuntu-14-04
php -v = PHP 7.07
But in Shopware Backend the is still PHP Version 5.5.9-1ubuntu4.9

I think i need some help

**Comment by sebastien-fauvel** [comment]
Have you already restarted apache with `sudo apachectl restart`?

**Comment by BlueWolf-Produktion** [comment]
That wont change anything. When i type **php -v**  i´ll get **PHP 7.0.7-1...**
In Shopware System Info the it is still 5.5.9

**Comment by sebastien-fauvel** [comment]
How about uninstalling php5 first?

**Comment by BlueWolf-Produktion** [comment]
I don´t know anything about linux - sorry. So i need a full 'howto' to change the php version on the system. I´d just found the howto above with google, but there seems to be something i can´t find on the system thats setting the php version for shopware / vagrant...
