### ISSUE TITLE
Vagrant was unable to mount VirtualBox shared folders

### ISSUE THREAD

**Issue by macidev** [shopwareLabs/shopware-vagrant#52]
Hi, 

on my Mac (10.13.6) with Vagrant 2.2.5 and Virtualbox 6.0.8 I got after a working installation and restarting the vagrant machine following error: 

> Vagrant was unable to mount VirtualBox shared folders. This is usually
> because the filesystem "vboxsf" is not available. This filesystem is
> made available via the VirtualBox Guest Additions and kernel module.
> Please verify that these guest additions are properly installed in the
> guest. This is not a bug in Vagrant and is usually caused by a faulty
> Vagrant box. For context, the command attempted was:
> 
> mount -t vboxsf -o uid=1000,gid=1000 vagrant /vagrant
> 
> The error output from the command was:
> 
> /sbin/mount.vboxsf: mounting failed with the error: No such device

The issue only occurs, if I restart, after install the box is working fine, but with vagrant ssh a restart is required. 

If there's anything further you need, please let me know.

**Comment by f0x7C0** [comment]
This seems to be an issue with your vagrant installation. Please make sure, that you have all necessary plugins installed to use shared / synced folders. There are some limitations with Windows OS when dealing with synced folders.

https://www.vagrantup.com/docs/synced-folders/nfs.html

**Comment by xcony** [comment]
install:
vagrant plugin vbguest

**Comment by macidev** [comment]
Installing the vbguest didn't work. So I searched for a solution. After I installed https://github.com/dotless-de/vagrant-vbguest locally on my Mac, setting 

`Vagrant.configure("2") do |config|
  config.vbguest.auto_update = true
end` 

in my `~/.vagrant.d/Vagrantfile`
and after that a vagrant up -> all went fine. Thanks.

**Comment by kadirsahan** [comment]
same problem is solved when upgrade the virtual box
