### ISSUE TITLE
Update default php version

### ISSUE THREAD

**Issue by HerHde** [shopwareLabs/shopware-vagrant#60]
Shopware reports:

`Your server is running PHP version 7.0.33-13+ubuntu16.04.1+deb.sury.org+1 but Shopware 5 requires at least PHP 7.2.0`

I guess it would be useful to set the default to PHP 7.2.

**Comment by tkomoszeski** [comment]
I created PR here :
https://github.com/shopwareLabs/shopware-vagrant/pull/62
